#ifndef _STREAMINGNOLOGY_MEDIASERVER_SNYREVISION_H_
#define _STREAMINGNOLOGY_MEDIASERVER_SNYREVISION_H_
#include <string>

const std::string MEDIASERVER_GIT_REVISION =	"master.0bf83305cc3cf3106bb9cf1369ebb8da77421477";
const std::string MEDIASERVER_BUILD_TIME   = "Aug.18.2018";

#endif //!_STREAMINGNOLOGY_MEDIASERVER_SNYREVISION_H_
