#ifndef _STREAMINGNOLOGY_CORE_TESTAPPLICATION_TEST_GPAC_H_
#define _STREAMINGNOLOGY_CORE_TESTAPPLICATION_TEST_GPAC_H_

#include <stdio.h>

void test_gpac(void);

#endif /* _STREAMINGNOLOGY_CORE_TESTAPPLICATION_TEST_GPAC_H_ */
